### PR TITLE
Upgrade to redis-classy 2.0; fixes issue #2

### PR DESCRIPTION
**Pull request by thiagofigueiro**
Fixes https://github.com/shaiguitar/resque_stuck_queue/issues/2

### CODE REVIEW

**Comment by dnishimura** [comment]
Is this gem no longer maintained?

**Comment by thiagofigueiro** [comment]
Looks that way.

**Comment by shaiguitar** [comment]
Sorry! Not sure how I missed this.

**Comment by shaiguitar** [comment]
Hey there @thiagofigueiro @dnishimura @apraditya @hackerrdave

Merged and uploaded to rubygems: https://rubygems.org/gems/resque_stuck_queue/versions/0.5.2

I've used this before but I don't use this currently, so if any of you do and would like upload permissions and want to take over, I'm happy to pass the baton on with a `gem owner` or what not.

Thanks for the contrib! Sorry about the lag.

**Comment by thiagofigueiro** [comment]
Hi, @shaiguitar - I'm happy to share the load but not completely take-over.  I can help review PRs, merge and coordinate/execute releases.

**Pull request merged**
